server:
  port: 8003
  
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml
  mapper-locations:
    - classpath:mybatis/mapper/**/*.xml
  type-aliases-package: com.atguigu.springcloud.entity

spring:
  application:
    name: provider
  datasource:
    password: root
    username: root
    url: jdbc:mysql://localhost:3306/clouddb03
    driver-class-name: org.gjt.mm.mysql.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    dbcp2:
      initial-size: 5
      min-idle: 5
      max-total: 5
      max-wait-millis: 200

eureka:
  client:
    service-url:
      defaultZone:  http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka
  instance:
    instance-id: provider8003-dept
    prefer-ip-address: true
      