server:
  port: 8001
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml
  mapper-locations:
    - classpath:mybatis/mapper/**/*.xml
  type-aliases-package: com.atguigu.springcloud.entity

spring:
  application:
    name: provider
  datasource:
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/clouddb01
    dbcp2:
      initial-size: 5
      max-total: 5
      min-idle: 5
      max-wait-millis: 200
   
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka
  instance:
    instance-id: provider8001-dept
    prefer-ip-address: true
    
info:
  app.name: atguigu-provider8001
  company.name: www.atguigu.com
  build.version:  $project.version$
  build.artifactId: $project.artifactId$
      
    